# auto delete old crash dumps
delete-files: false
# how long crash dumps should remain untouched (in hours), only needed if delete-files is true
validity-duration: 24

# report crash dumps to a discord channel
report-crash: false
# announces a crash report. This prevents a crash being overlooked due to the plugin malfunctioning
announce-crash-report: true
# This plugin assumes that the server folder name is an informative description of the server.
# If this isn't the case, you can enable the usage of the full server path to ensure an unambiguous crash report.
announce-full-path: false
# webhook url obtained from discord
webhook-url: ""
# format for the server time field. Look up this page for reference: https://www.php.net/manual/en/datetime.format.php
date-format: "d.m.Y (l): H:i:s [e]"
